public class JobbleResponse {
    public JobbleResponse() {
        Integer jobCount;
    }

    public class jobList {
        public String title;	//BI Developer 3 - Central (H)
        public String location;	//Miami, FL
        public String snippet;	//&nbsp;...The University of Miami Health System, "UHealth", IT Department has an exciting opportunity for a Full-time BI <b>Developer </b>3. The BI Developer with expertise in SQL, ETL processes, dashboard development, and Epic applications. This position will manage data infrastructure...&nbsp;
        public String salary;	//$50 - $60 per hour
        public String source;	//sonicjobs.com
        public String type;	    //Full-timee
        public String link;	    //https://jooble.org/desc/3238258985563707791?ckey=Salesforce+developer&rgn=9649&pos=1&groupId=40906&elckey=7321960120849852300&p=1&aq=7400284639310049157&cid=5537&jobAge=970&brelb=10&bscr=10.730836&scr=10.730836
        public String company;	//University of Miami Health System
        public String updated;	//2025-06-12T00:00:00.0000000
        public String joobleId;	//
    }

    

}